### ISSUE TITLE
I download and install the HUSTElecBill，but it can't find its entrance

### ISSUE THREAD

**Issue by Kyle-Ye** [LewisTian/PyQt5-Apps#1]
![image](https://user-images.githubusercontent.com/43724855/48299796-48972280-e50d-11e8-8266-158a0bd435f1.png)
如图，这种错误应该怎么解决呢？（按网上方法试了下：直接手动注册不行，拷贝到System子目录下注册还是不行）

**Comment by taseikyo** [comment]
@Kyle-YeXuLei 我也不知道为什么会出现这个问题:astonished:不行你就自己下载源码运行吧_(:з)∠)_

**Comment by taseikyo** [comment]
@Kyle-YeXuLei 我在我新电脑上下载运行没问题啊_(:з)∠)_这就很迷了...

**Comment by Kyle-Ye** [comment]
好的，谢谢学长了

**Comment by taseikyo** [comment]
学长是什么鬼:no_mouth:
