### ISSUE TITLE
QSS文件的问题

### ISSUE THREAD

**Issue by FontaineGuo** [LewisTian/PyQt5-Apps#3]
请问一下QSS文件能否再编辑的时候即使的通过诸如QT Designer这种工具进行预览？如果不能预览，那么在调试的过程中，能有有一些经验可以分享？

**Comment by taseikyo** [comment]
@FontaineGuo 关于在 Qt Creator 中设置样式的问题，我就知道两种方法
第一个是对每个控件单独设置 styleSheet 属性 这种是可以直接显示效果的
第二个是在 main.cpp 中加载 qss 文件 在运行之后生效
估计你说的应该是第二种吧

**Comment by FontaineGuo** [comment]
好的 谢谢分享!
