### ISSUE TITLE
[feature request] hust-electricity-fee

### ISSUE THREAD

**Issue by recolic** [LewisTian/PyQt5-Apps#4]
你好，这个小项目因为华科没有人抓过API，所以很有实际应用价值。可否分离成一个单独的仓库，我希望继续开发跨平台的版本，

**Comment by taseikyo** [comment]
这其实就是个爬虫，从 http://202.114.18.218/Main.aspx 这个网站拿到的数据
代码都在对应的目录下，要是想继续开发直接拿去用就行了，懒得单独开个仓了😂

**Comment by recolic** [comment]
emm还是华科内网。。打扰了
