### ISSUE TITLE
文件夹浏览

### ISSUE THREAD

**Issue by wangyexiang** [LewisTian/PyQt5-Apps#6]
![图片](https://user-images.githubusercontent.com/23202109/69787136-d2885b00-11f6-11ea-93d2-ed55eb54057b.png)

请问一下，window系统下，如何实现的这种类似于浏览器的功能？是clover吗？

**Comment by taseikyo** [comment]
我用的就是 Clover

**Comment by wangyexiang** [comment]
多谢。@taseikyo
