### ISSUE TITLE
.ui文件

### ISSUE THREAD

**Issue by DelinQu** [LewisTian/PyQt5-Apps#8]
作者您好，最近在学习pyQt ，看到您的 `bilibili-kit` 感觉设计得很不错，想临摹学习一番。但是不太会用pyQt Designer设计界面，请问可以分享一份`bilibili-kit`的.ui文件吗？感激不尽！

**Comment by taseikyo** [comment]
这个好像是最早做的那批，那个时候只把转的 py 文件放到 GitHub 而忘记存 ui 文件了
后来不小心把 Qt 那个工程目录删了，所以那批应用的 ui 文件都没了😂

直接在 Qt 里面拖控件也不难，根据需要放置各个布局、控件就完了，要是想做你可以试着自己做一样
